<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { TodoDB, ExpenseDB, SettingsDB } from '../services/db'
import { compressImage } from '../services/image'
import { today, formatCurrency, CATEGORY_ICONS } from '../utils/format'
import type { TodoItem, Expense } from '../types'

const router = useRouter()

// Toast
const toast = ref({ show: false, msg: '', type: 'success' })
function showToast(msg: string, type = 'success') {
  toast.value = { show: true, msg, type }
  setTimeout(() => { toast.value.show = false }, 2000)
}

// 进度环
const todos = ref<TodoItem[]>([])
const completedCount = computed(() => todos.value.filter(t => t.completed).length)
const progressPercent = computed(() => {
  if (todos.value.length === 0) return 0
  return Math.round((completedCount.value / todos.value.length) * 100)
})
const circumference = 2 * Math.PI * 45
const dashOffset = computed(() => circumference * (1 - progressPercent.value / 100))

// 今日消费
const todayExpenses = ref<Expense[]>([])
const todayTotal = computed(() => todayExpenses.value.reduce((sum, e) => sum + e.amount, 0))

// 快捷记账浮窗
const showQuickExpense = ref(false)
const quickAmount = ref('')
const quickCategory = ref<Expense['category']>('餐饮')
const quickNote = ref('')
const quickImage = ref('')
const quickImagePreview = ref('')
const categories: Expense['category'][] = ['餐饮', '购物', '交通', '娱乐', '医疗', '其他']

// 拍照 / 相册 两个入口
const cameraInput = ref<HTMLInputElement | null>(null)
const albumInput = ref<HTMLInputElement | null>(null)
function pickCamera() { cameraInput.value?.click() }
function pickAlbum() { albumInput.value?.click() }

async function handleImageUpload(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (!file) return
  const compressed = await compressImage(file)
  quickImage.value = compressed
  quickImagePreview.value = compressed
  input.value = ''
}

async function submitQuickExpense() {
  const amount = parseFloat(quickAmount.value)
  if (!amount || amount <= 0) { showToast('请输入有效金额', 'error'); return }
  await ExpenseDB.add({
    date: today(),
    amount,
    category: quickCategory.value,
    note: quickNote.value,
    imageBase64: quickImage.value,
    createdAt: new Date().toISOString()
  })
  showQuickExpense.value = false
  quickAmount.value = ''
  quickNote.value = ''
  quickImage.value = ''
  quickImagePreview.value = ''
  showToast('记账成功！')
  loadData()
}

async function toggleTodo(todo: TodoItem) {
  todo.completed = !todo.completed
  todo.completedAt = todo.completed ? new Date().toISOString() : undefined
  await TodoDB.update(todo)
  loadData()
}

async function deleteTodo(id: number) {
  await TodoDB.delete(id)
  loadData()
  showToast('已删除')
}

async function addTodo() {
  const content = prompt('添加新任务：')
  if (!content) return
  await TodoDB.add({
    content,
    completed: false,
    isHighPriority: false,
    isAutoGenerated: false,
    date: today(),
    createdAt: new Date().toISOString()
  })
  loadData()
  showToast('任务已添加')
}

async function loadData() {
  const allTodos = await TodoDB.getAll()
  const allExpenses = await ExpenseDB.getAll()
  todayExpenses.value = allExpenses.filter(e => e.date === today()).sort(
    (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
  )
  todos.value = allTodos.filter(t => !t.completed || t.date === today()).sort(
    (a, b) => {
      if (a.completed !== b.completed) return a.completed ? 1 : -1
      return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
    }
  ).slice(0, 8)
}

// 自动生成每日任务
async function autoGenerateTodos() {
  const existing = await TodoDB.getByDate(today())
  const hasAutoGen = existing.some(t => t.isAutoGenerated)
  if (hasAutoGen) return

  const settings = await SettingsDB.get()
  const plans = settings.sportPlans || []
  const weekday = new Date().getDay()

  const autoItems = [{ content: '📚 完成今日英语学习打卡', module: 'learning' }]

  const todayPlan = plans.find(p => p.weekday === weekday)
  if (todayPlan) {
    autoItems.push({ content: `🏃 ${todayPlan.type} ${todayPlan.duration}分钟`, module: 'sport' })
  } else {
    autoItems.push({ content: '🏃 完成今日运动计划', module: 'sport' })
  }

  autoItems.push({ content: '🤖 查看今日AI资讯', module: 'ai' })

  for (const item of autoItems) {
    await TodoDB.add({
      content: item.content,
      completed: false,
      isHighPriority: false,
      isAutoGenerated: true,
      sourceModule: item.module,
      date: today(),
      createdAt: new Date().toISOString()
    })
  }
}

onMounted(async () => {
  await autoGenerateTodos()
  loadData()
})
</script>

<template>
  <div>
    <!-- Toast -->
    <div v-if="toast.show" class="toast" :class="toast.type">{{ toast.msg }}</div>

    <!-- 进度环 -->
    <div class="card" style="text-align: center;">
      <div class="progress-ring" style="width: 120px; height: 120px;">
        <svg width="120" height="120" viewBox="0 0 120 120">
          <circle cx="60" cy="60" r="45" fill="none" stroke="var(--border)" stroke-width="8" />
          <circle
            cx="60" cy="60" r="45" fill="none" stroke="var(--primary)" stroke-width="8"
            stroke-linecap="round" :stroke-dasharray="circumference"
            :stroke-dashoffset="dashOffset"
            style="transition: stroke-dashoffset 0.5s ease;"
          />
        </svg>
        <div class="progress-text">{{ progressPercent }}%</div>
      </div>
      <div style="margin-top: 8px; color: var(--text-secondary); font-size: 13px;">
        已完成 {{ completedCount }}/{{ todos.length }} 项任务
      </div>
    </div>

    <!-- Todo 列表 -->
    <div class="card">
      <div class="card-title">📝 今日任务</div>
      <div v-if="todos.length === 0" class="empty-state">
        <div class="icon">✨</div>
        <div>暂无任务，开始新的一天吧</div>
      </div>
      <div v-for="todo in todos" :key="todo.id" style="display: flex; align-items: center; gap: 10px; padding: 10px 0; border-bottom: 1px solid var(--border);">
        <input
          type="checkbox"
          :checked="todo.completed"
          @change="toggleTodo(todo)"
          style="width: 20px; height: 20px; accent-color: var(--primary); flex-shrink: 0;"
        />
        <span
          :style="{
            flex: 1, fontSize: '14px',
            textDecoration: todo.completed ? 'line-through' : 'none',
            color: todo.completed ? 'var(--text-muted)' : 'var(--text-primary)'
          }"
        >
          <span v-if="todo.isHighPriority" style="color: var(--danger); margin-right: 4px;">🔴</span>
          {{ todo.content }}
        </span>
        <button class="btn btn-sm" style="color: var(--danger);" @click="deleteTodo(todo.id!)">✕</button>
      </div>
      <button class="btn btn-primary btn-sm" style="margin-top: 12px;" @click="addTodo">+ 添加任务</button>
    </div>

    <!-- 今日消费速记 -->
    <div class="card">
      <div class="card-title">💳 今日消费</div>
      <div v-if="todayExpenses.length === 0" class="empty-state" style="padding: 20px;">
        <div style="font-size: 32px;">💸</div>
        <div>今天还没有消费记录</div>
      </div>
      <div v-else>
        <div style="font-size: 24px; font-weight: 700; color: var(--danger); margin-bottom: 12px;">
          {{ formatCurrency(todayTotal) }}
        </div>
        <div v-for="e in todayExpenses.slice(0, 3)" :key="e.id"
          style="display: flex; align-items: center; gap: 10px; padding: 8px 0; font-size: 13px;">
          <span>{{ CATEGORY_ICONS[e.category] }}</span>
          <span style="flex: 1;">{{ e.note || e.category }}</span>
          <span style="font-weight: 600;">{{ formatCurrency(e.amount) }}</span>
        </div>
      </div>
      <button class="btn btn-primary btn-sm" style="margin-top: 12px;" @click="showQuickExpense = true">
        💰 快速记账
      </button>
    </div>

    <!-- 快捷入口 -->
    <div class="quick-actions">
      <button class="quick-action-btn" @click="router.push('/english')">
        <span class="qa-icon">📚</span>
        <span class="qa-label">英语打卡</span>
      </button>
      <button class="quick-action-btn" @click="router.push('/sport')">
        <span class="qa-icon">🏃</span>
        <span class="qa-label">今日运动</span>
      </button>
      <button class="quick-action-btn" @click="router.push('/focus-mode')">
        <span class="qa-icon">🎯</span>
        <span class="qa-label">专注模式</span>
      </button>
      <button class="quick-action-btn" @click="router.push('/ai-news')">
        <span class="qa-icon">🔍</span>
        <span class="qa-label">AI 资讯</span>
      </button>
    </div>

    <!-- 快速记账浮窗 -->
    <div v-if="showQuickExpense" class="modal-overlay" @click.self="showQuickExpense = false">
      <div class="modal">
        <div class="modal-header">
          <h3>💰 快速记账</h3>
          <button class="modal-close" @click="showQuickExpense = false">✕</button>
        </div>

        <div class="form-group">
          <label class="form-label">金额</label>
          <input v-model="quickAmount" class="input" type="number" placeholder="0.00" step="0.01" min="0" />
        </div>

        <div class="form-group">
          <label class="form-label">分类</label>
          <div style="display: flex; gap: 6px; flex-wrap: wrap;">
            <button
              v-for="cat in categories" :key="cat"
              class="btn btn-sm"
              :class="quickCategory === cat ? 'btn-primary' : 'btn-secondary'"
              @click="quickCategory = cat"
            >
              {{ CATEGORY_ICONS[cat] }} {{ cat }}
            </button>
          </div>
        </div>

        <div class="form-group">
          <label class="form-label">备注</label>
          <input v-model="quickNote" class="input" placeholder="可选备注" />
        </div>

        <div class="form-group">
          <label class="form-label">凭证图片</label>
          <div style="display: flex; gap: 8px;">
            <button type="button" class="btn btn-sm btn-secondary" @click="pickCamera">📷 拍照</button>
            <button type="button" class="btn btn-sm btn-secondary" @click="pickAlbum">🖼️ 相册</button>
          </div>
          <input ref="cameraInput" type="file" accept="image/*" capture="environment" style="display: none;" @change="handleImageUpload" />
          <input ref="albumInput" type="file" accept="image/*" style="display: none;" @change="handleImageUpload" />
          <img v-if="quickImagePreview" :src="quickImagePreview" style="width: 100%; border-radius: 8px; margin-top: 8px; max-height: 200px; object-fit: cover;" />
        </div>

        <button class="btn btn-primary btn-block" @click="submitQuickExpense" :disabled="!quickAmount">
          ✓ 确认记账
        </button>
      </div>
    </div>
  </div>
</template>
