// ====== 类型定义 ======

export interface LearningRecord {
  id?: number
  date: string
  category: string
  content: string
  isFavorite: boolean
  createdAt: string
}

export interface SportRecord {
  id?: number
  date: string
  type: string
  duration: number // 分钟
  createdAt: string
}

export interface SportPlan {
  weekday: number // 0-6 周日-周六
  type: string
  duration: number
}

/** 运动学习资料（用户自行添加的视频） */
export interface SportVideo {
  id?: number
  title: string
  category: string       // 游泳 / 肩背 / 臀腿 / 爬坡 / 攀岩 / 其他
  sourceType: 'link' | 'file'
  url?: string           // link 模式：B站/YouTube/直链
  blob?: Blob            // file 模式：本地视频文件
  note?: string
  createdAt: string
}

/** 运动类别关联的教程 / 视频链接（可跳转平台 App） */
export interface SportLink {
  id?: number
  type?: string          // 兼容旧数据：单类别（已废弃，保留用于迁移）
  types?: string[]       // 可分配到多个运动类别，统一教程库分配使用
  platform: string       // 小红书 / 抖音 / B站 / YouTube / 其他（自动识别）
  url: string
  note?: string
  createdAt: string
}

export interface Expense {
  id?: number
  date: string
  amount: number
  category: '餐饮' | '购物' | '交通' | '娱乐' | '医疗' | '其他'
  note: string
  imageBase64: string
  type?: 'expense' | 'income'  // 收支类型：缺省视为支出（兼容旧数据）
  createdAt: string
}

export interface TodoItem {
  id?: number
  content: string
  completed: boolean
  isHighPriority: boolean
  isAutoGenerated: boolean
  sourceModule?: string
  date: string
  completedAt?: string
  createdAt: string
}

/** RSS 抓取 / 手动录入的资讯条目 */
export interface NewsItem {
  id?: number
  title: string
  link: string
  summary: string
  source: string          // 来源站点名
  category: string        // 新技术 / 新产品 / 新开源 / 新点子
  pubDate: string         // ISO
  isRead: boolean
  isFavorite: boolean
  syncedToFeishu?: boolean
  createdAt: string
}

/** RSS 订阅源 */
export interface NewsSource {
  id: string
  name: string
  url: string
  enabled: boolean
  builtin: boolean
}

export interface AppSettings {
  // 飞书配置
  feishuAppId: string
  feishuAppSecret: string
  feishuAppToken: string
  feishuAiNewsTableId: string
  feishuDailyBriefsTableId: string
  // 大模型配置
  llmApiKey: string
  llmProvider: 'deepseek' | 'siliconflow' | 'lingyi' | 'none'
  llmModel?: string        // 具体模型名；为空时回退到厂商默认模型
  // 运动计划
  sportPlans: SportPlan[]
  // 专注设置
  focusDuration: number
  focusSoundVolume: number
  // 资讯源
  newsSources: NewsSource[]
  newsLastFetch: string
  // 腾讯文档快捷入口
  tencentDocUrl: string
  // 主题
  theme: 'auto' | 'light' | 'dark'
}

export interface DailyBrief {
  id?: number
  date: string
  title: string
  content: string
  newsCount: number
  createdAt: string
}

// 飞书 API 响应类型
export interface FeishuTokenResponse {
  code: number
  msg: string
  tenant_access_token: string
  expire: number
}

export interface FeishuRecordsResponse {
  code: number
  msg: string
  data: {
    has_more: boolean
    items: FeishuRecordItem[]
    page_token?: string
    total: number
  }
}

export interface FeishuRecordItem {
  record_id: string
  fields: Record<string, unknown>
}

export interface ExpenseStats {
  total: number
  byCategory: Record<string, number>
  daily: { date: string; amount: number }[]
}

// ====== 英语学习资料 ======
export interface EnglishItem { en: string; zh: string }
export interface EnglishParagraph { title: string; en: string; zh: string }
export interface EnglishDialogueLine { role: string; en: string; zh: string }

export interface EnglishLesson {
  id: string
  theme: string           // 主题名
  emoji: string
  level: '入门' | '进阶' | '高阶'
  desc?: string           // 单元描述 / 适用场景
  custom?: boolean        // 是否为用户自建单元
  createdAt?: string
  phrases: EnglishItem[]              // 短语池（分批展示，可刷新）
  sentences: EnglishItem[]            // 句子池（分批展示，可刷新）
  paragraphs: EnglishParagraph[]      // 段落池（可刷新换一篇）
  dialogues: EnglishDialogueLine[][]  // 口语练习池（可刷新换一段）
  tips: string[]
}

/** 英语每日打卡（四个学习块全部 100% 完成才记一次） */
export interface EnglishCheckIn {
  id?: number
  date: string            // YYYY-MM-DD
  lessonId: string
  lessonTheme: string
  createdAt: string
}

// ====== 运动训练资料 ======
export interface SportGuide {
  id: string
  name: string
  emoji: string
  intro: string
  warmup: string[]
  actions: { name: string; detail: string; sets: string; key: string }[]
  cooldown: string[]
  mistakes: string[]
  refKeyword: string      // 推荐搜索关键词（用于找教学视频）
}
