// ====== 类型定义 ======

export interface LearningRecord {
  id?: number
  date: string
  category: string
  content: string
  isFavorite: boolean
  createdAt: string
}

export interface SportRecord {
  id?: number
  date: string
  type: string
  duration: number // 分钟
  createdAt: string
}

export interface SportPlan {
  weekday: number // 0-6 周日-周六
  type: string
  duration: number
}

export interface Expense {
  id?: number
  date: string
  amount: number
  category: '餐饮' | '购物' | '交通' | '娱乐' | '医疗' | '其他'
  note: string
  imageBase64: string
  createdAt: string
}

export interface TodoItem {
  id?: number
  content: string
  completed: boolean
  isHighPriority: boolean
  isAutoGenerated: boolean
  sourceModule?: string
  date: string
  completedAt?: string
  createdAt: string
}

export interface AppSettings {
  // 飞书配置
  feishuAppId: string
  feishuAppSecret: string
  feishuAppToken: string
  feishuAiNewsTableId: string
  feishuShopMaterialsTableId: string
  feishuDailyBriefsTableId: string
  // 大模型配置
  llmApiKey: string
  llmProvider: 'deepseek' | 'siliconflow' | 'lingyi' | 'none'
  // 运动计划
  sportPlans: SportPlan[]
  // 专注设置
  focusDuration: number
  // 数据源
  dataSourceUrl: string
  // 主题
  theme: 'auto' | 'light' | 'dark'
}

export interface AiNewsRecord {
  id?: number
  title: string
  link: string
  summary: string
  category: string
  createdAt: string
}

export interface ShopMaterial {
  id?: number
  title: string
  tags: string[]
  category: string
  content: string
  sourceLink: string
  createdAt: string
}

export interface DailyBrief {
  id?: number
  date: string
  title: string
  content: string
  newsCount: number
  materialCount: number
  createdAt: string
}

// 飞书 API 响应类型
export interface FeishuTokenResponse {
  code: number
  msg: string
  tenant_access_token: string
  expire: number
}

export interface FeishuRecordsResponse {
  code: number
  msg: string
  data: {
    has_more: boolean
    items: FeishuRecordItem[]
    page_token?: string
    total: number
  }
}

export interface FeishuRecordItem {
  record_id: string
  fields: Record<string, unknown>
}

export interface ExpenseStats {
  total: number
  byCategory: Record<string, number>
  daily: { date: string; amount: number }[]
}
